# Generated by Django 3.0.4 on 2021-03-10 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20210305_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.PositiveIntegerField(blank=True, help_text='Diffficulty level for the questions', null=True, verbose_name='Difficulty'),
        ),
    ]
