# Generated by Django 3.0.4 on 2021-03-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20210310_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.PositiveIntegerField(blank=True, help_text='Diffficulty level for the questions', null=True, verbose_name='Difficulty'),
        ),
    ]
