# Generated by Django 3.0.4 on 2021-03-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_question_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizprofile',
            name='ip',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Individual Proficiency'),
        ),
    ]
